language: ruby
cache: bundler
rvm:
  - 2.3.1
  - 1.9.3
  - jruby-19mode
env:
  global:
    - TRAVIS=true
  matrix:
    - DB=mysql
    - DB=postgres
    - DB=sqlite

sudo: false

before_script:
  - mysql --version
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql   -e 'create database paper_trail_test;'; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql   -e 'create database paper_trail_bar; '; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql   -e 'create database paper_trail_foo; '; fi"
  - psql --version
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database paper_trail_test;' -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database paper_trail_bar;'  -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database paper_trail_foo;'  -U postgres; fi"

gemfile:
  - gemfiles/ar3.gemfile
  - gemfiles/ar4.gemfile
  - gemfiles/ar5.gemfile
  - gemfiles/ar_master.gemfile

matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/ar5.gemfile
      rvm: 1.9.3
    - gemfile: gemfiles/ar5.gemfile
      rvm: jruby-19mode
  allow_failures:
    - gemfile: gemfiles/ar_master.gemfile

addons:
  postgresql: "9.4"
