language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-19mode
  - jruby-18mode
env:
  global:
    - TRAVIS=true
  matrix:
    - DB=mysql
    - DB=postgres
    - DB=sqlite

sudo: false

before_script:
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql   -e 'create database paper_trail_test;'; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql   -e 'create database paper_trail_bar; '; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql   -e 'create database paper_trail_foo; '; fi"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database paper_trail_test;' -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database paper_trail_bar;'  -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database paper_trail_foo;'  -U postgres; fi"

gemfile:
  - Gemfile
  - gemfiles/3.0.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-18mode
      gemfile: Gemfile
    - rvm: 1.8.7
      gemfile: Gemfile

addons:
  postgresql: "9.4"
